// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
/// 
import "dotenv/config";

export default {
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // في JavaScript نحذف "as string" لأنها غير موجودة في اللغة
    url: process.env.DATABASE_URL, 
  },
};
